In [1]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [4]:
# Rótulos binários reais (Ex.: Sobreviveu = 1, Morreu = 0)
y_true = np.array([1, 0, 1, 1, 0, 1, 0, 0, 1, 0])

# Previsões de modelo (Ex.: Previsões de sobrevivência)
y_pred = np.array([1, 1, 1, 0, 0, 1, 0, 1, 1, 0])

# 1. Matriz de Confusão
# [[VN, FP],
# [FN, VP]]
matriz = confusion_matrix(y_true, y_pred)
print("1. Matriz de Confusão:")
print(matriz)
# Neste exemplo: VN = 3, FP = 2, FN = 1, VP = 4

# 2. Acurácia
acuracia = accuracy_score(y_true, y_pred)
print(f"\n2. Acurácia: {acuracia:.2f}")

# 3. Precisão | Foco: Evitar falsos positivos (FP)
precisao = precision_score(y_true, y_pred)
print(f"\n3. Precisão: {precisao:.2f}")

# 4. Revocação | Foco: Evitar falsos negativos (FN)
revocacao = recall_score(y_true, y_pred)
print(f"\n4. Recall: {revocacao:.2f}")

# 5. F1-Score (equilíbrio)
f1 = f1_score(y_true, y_pred)
print(f"\n5. F1-Score: {f1:.2f}")

1. Matriz de Confusão:
[[3 2]
 [1 4]]

2. Acurácia: 0.70

3. Precisão: 0.67

4. Recall: 0.80

5. F1-Score: 0.73


In [5]:
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [8]:
# 1. Gerar dataset artificial (2 luas com ruído)
X, y = make_moons(n_samples=500, noise=0.3, random_state=42)

# 2. Separar em treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Decision Tree SEM limiar de profundidade (overfitting)
arvore = DecisionTreeClassifier(random_state=42)
arvore.fit(X_train, y_train)
y_pred_arvore = arvore.predict(X_test)

# 4. Random Forest
floresta = RandomForestClassifier(random_state=42)
floresta.fit(X_train, y_train)
y_pred_floresta = floresta.predict(X_test)

# Métricas
# Acurácia
print("--- Resultados Acurácia ---")
print(f"Decision Tree - Treino:", accuracy_score(y_train, arvore.predict(X_train)))
print(f"Decision Tree - Teste:", accuracy_score(y_test, y_pred_arvore))
print(f"Random Forest - Treino:", accuracy_score(y_train, floresta.predict(X_train)))
print(f"Random Forest: - Teste", accuracy_score(y_test, y_pred_floresta))

print("\n--- Decision Tree ---")
print("Matriz de Confusão:\n", confusion_matrix(y_test, y_pred_arvore))
print(f"Precisão: {precision_score(y_test, y_pred_arvore):.4f}")
print(f"Revocação: {recall_score(y_test, y_pred_arvore):.4f}")
print(f"F1-Score: {f1_score(y_test, y_pred_arvore):.4f}")

print("\n--- Random Forest ---")
print("Matriz de Confusão:\n", confusion_matrix(y_test, y_pred_floresta))
print(f"Precisão: {precision_score(y_test, y_pred_floresta):.4f}")
print(f"Revocação: {recall_score(y_test, y_pred_floresta):.4f}")
print(f"F1-Score: {f1_score(y_test, y_pred_floresta):.4f}")

--- Resultados Acurácia ---
Decision Tree - Treino: 1.0
Decision Tree - Teste: 0.82
Random Forest - Treino: 1.0
Random Forest: - Teste 0.88

--- Decision Tree ---
Matriz de Confusão:
 [[38  5]
 [13 44]]
Precisão: 0.8980
Revocação: 0.7719
F1-Score: 0.8302

--- Random Forest ---
Matriz de Confusão:
 [[43  0]
 [12 45]]
Precisão: 1.0000
Revocação: 0.7895
F1-Score: 0.8824
